#!/bin/bash
#SBATCH --job-name=NEBa
#SBATCH -p RM-shared
#SBATCH -N 1
#SBATCH --ntasks=25
#SBATCH -t 9:00:00

module purge
module load gcc/10.2.0
module load openmpi/4.0.5-gcc10.2.0
module load intel-mkl

ulimit -s unlimited

# 3. Handle the library paths
export LD_LIBRARY_PATH=$MKLROOT/lib/intel64:$LD_LIBRARY_PATH

cd /ocean/projects/mat250017p/desantos/projects/NEBCrosslinkWork/NEBanalog_a

# --- TIMER START ---
START_TIME=$(date +%s)
echo "------------------------------------------------"
echo "Job started at: $(date)"
echo "------------------------------------------------"

# Use --overload-allowed if you really want to run 60 tasks on fewer than 60 cores
# But for DFT (SeqQuest), it's better to run 1 task per 1 physical core.
mpirun -np $SLURM_NTASKS --bind-to none /ocean/projects/mat250017p/desantos/seqquest_parallel/quest_265a.x


# --- TIMER END ---
END_TIME=$(date +%s)
DURATION=$((END_TIME - START_TIME))

# Convert seconds to HH:MM:SS for readability
HOURS=$((DURATION / 3600))
MINUTES=$(( (DURATION % 3600) / 60 ))
SECONDS=$((DURATION % 60))

echo "------------------------------------------------"
echo "Job ended at: $(date)"
echo "Total Runtime: ${HOURS}h ${MINUTES}m ${SECONDS}s"
echo "------------------------------------------------"